/**
 * Wave 1 Track A — v2.1 methodology re-validation against the 64 rescraped utilities.
 *
 * Compares Calculator outputs (bill impact, revenue adequacy ratio, demand-charge
 * flow-through %) using:
 *   - Baseline tariff data: `lib/generatedTariffData.baseline-jan2026.ts`
 *     (Jan 2026 snapshot extracted from SHA `ab74e83`, pre-Hermes-rescrape;
 *     this is what Gemini originally reviewed for the v2.1 methodology bless)
 *   - Refreshed tariff data: `lib/generatedTariffData.ts` (current — 64 rescraped
 *     via Hermes 2026-05-14 / 2026-05-17, 24 still on Jan 2026 baseline)
 *
 * Utilities included: every entry in the current generatedTariffData.ts whose
 * `last_verified ∈ { '2026-05-14', '2026-05-17' }` — the rescraped 64.
 *
 * Scenarios per utility (5):
 *   1. 1 GW firm 24/7 baseload (LF 0.95, peak coincidence 1.0)
 *   2. 1 GW flexible (LF 0.95, peak coincidence 0.75)
 *   3. DC penetration at 5% of systemPeakMW (firm baseload)
 *   4. DC penetration at 10% of systemPeakMW (firm baseload)
 *   5. DC penetration at 20% of systemPeakMW (firm baseload)
 *
 * Outputs:
 *   - `docs/track-e-deltas-2026-05-27.json` — full delta matrix (raw)
 *   - stdout — concise summary; `docs/GEMINI_REFRESH_DELTA_2026-05-27.md` is
 *     drafted by hand from the JSON, not auto-generated by this script
 *
 * Usage: `npx tsx scripts/track-e-delta-validation.ts`
 */

import { writeFileSync } from 'fs';
import { join } from 'path';

import {
    generateAllTrajectories,
    calculateRevenueAdequacy,
    calculateTariffBasedDemandCharges,
    type EscalationConfig,
    type RevenueAdequacyResult,
} from '../lib/calculations';
import {
    UTILITY_PROFILES,
    enrichedTariffToUtilityProfile,
    type UtilityProfile,
} from '../lib/utilityData';
import { GENERATED_TARIFFS } from '../lib/generatedTariffData';
import { BASELINE_TARIFF_DATA } from '../lib/generatedTariffData.baseline-jan2026';
import {
    DEFAULT_UTILITY,
    DEFAULT_DATA_CENTER,
    type Utility,
    type DataCenter,
} from '../lib/constants';

// ============================================================
// CONFIG
// ============================================================
const PROJECTION_YEARS = 12;
const ESCALATION: EscalationConfig = {
    inflationEnabled: false,
    inflationRate: 0.02,
    infrastructureAgingEnabled: false,
    infrastructureAgingRate: 0.01,
};
const RESCRAPED_VERIFIED_DATES = new Set(['2026-05-14', '2026-05-17']);

interface Scenario {
    label: string;
    capacityResolver: (profile: UtilityProfile) => number;
    loadFactor: number;
    peakCoincidence: number;
    series: 'unoptimized' | 'flexible';
    kind: 'fixed-1gw-firm' | 'fixed-1gw-flex' | 'penetration-firm';
    penetrationPct?: number;
}

const SCENARIOS: Scenario[] = [
    {
        label: '1GW firm 24/7 baseload',
        capacityResolver: () => 1000,
        loadFactor: 0.95,
        peakCoincidence: 1.0,
        series: 'unoptimized',
        kind: 'fixed-1gw-firm',
    },
    {
        label: '1GW flexible (LF 0.95, PC 0.75)',
        capacityResolver: () => 1000,
        loadFactor: 0.95,
        peakCoincidence: 0.75,
        series: 'flexible',
        kind: 'fixed-1gw-flex',
    },
    {
        label: '5% of system peak — firm baseload',
        capacityResolver: (p) => Math.max(50, p.systemPeakMW * 0.05),
        loadFactor: 0.95,
        peakCoincidence: 1.0,
        series: 'unoptimized',
        kind: 'penetration-firm',
        penetrationPct: 0.05,
    },
    {
        label: '10% of system peak — firm baseload',
        capacityResolver: (p) => Math.max(100, p.systemPeakMW * 0.10),
        loadFactor: 0.95,
        peakCoincidence: 1.0,
        series: 'unoptimized',
        kind: 'penetration-firm',
        penetrationPct: 0.10,
    },
    {
        label: '20% of system peak — firm baseload',
        capacityResolver: (p) => Math.max(200, p.systemPeakMW * 0.20),
        loadFactor: 0.95,
        peakCoincidence: 1.0,
        series: 'unoptimized',
        kind: 'penetration-firm',
        penetrationPct: 0.20,
    },
];

// ============================================================
// HELPER: replicate getUtilityById merge logic, parameterized on tariff pool
// (Same shape as scripts/refresh-delta-driver.ts buildProfileFromPool)
// ============================================================
type EnrichedLike = (typeof GENERATED_TARIFFS)[number];

function buildProfileFromPool(
    utilityId: string,
    tariffPool: EnrichedLike[],
): UtilityProfile | undefined {
    const manual = UTILITY_PROFILES.find((u) => u.id === utilityId);
    const tariff = tariffPool.find((t) => t.id === utilityId);

    if (manual && tariff) {
        const peakDemandCharge = (tariff.peak_demand_charge || 5) * 1000;
        const maxDemandCharge =
            (tariff.off_peak_demand_charge || tariff.peak_demand_charge * 0.4) * 1000;
        const energyCharge = tariff.blendedRatePerKWh * 1000;
        const ratchetPercent = tariff.protections.ratchet_pct
            ? tariff.protections.ratchet_pct / 100
            : manual.tariff.ratchetPercent;

        return {
            ...manual,
            state: tariff.state,
            tariff: {
                ...manual.tariff,
                peakDemandCharge,
                maxDemandCharge,
                energyCharge,
                ratchetPercent,
                ratchetMonths: ratchetPercent ? 12 : manual.tariff.ratchetMonths,
                tariffSource: `${tariff.tariff_name} (${tariff.rate_schedule}); ${manual.tariff.tariffSource}`,
            },
        };
    }
    if (manual) return manual;
    if (tariff) return enrichedTariffToUtilityProfile(tariff);
    return undefined;
}

function buildUtilityFromProfile(profile: UtilityProfile): Utility {
    return {
        ...DEFAULT_UTILITY,
        name: profile.name,
        state: profile.state,
        residentialCustomers: profile.residentialCustomers,
        averageMonthlyBill: profile.averageMonthlyBill,
        averageMonthlyUsage: profile.averageMonthlyUsageKWh,
        systemPeakMW: profile.systemPeakMW,
        baseResidentialAllocation: profile.market.baseResidentialAllocation,
        marketType: profile.market.type,
        hasCapacityMarket: profile.market.hasCapacityMarket,
        capacityCostPassThrough: profile.market.capacityCostPassThrough,
        capacityPrice2024: profile.market.capacityPrice2024,
        totalGenerationCapacityMW: profile.totalGenerationCapacityMW,
        currentReserveMargin: profile.currentReserveMargin,
        interconnection: profile.interconnection,
        marginalEnergyCost: profile.market.marginalEnergyCost,
    };
}

function buildDataCenter(scenario: Scenario, capacityMW: number): DataCenter {
    if (scenario.series === 'flexible') {
        return {
            ...DEFAULT_DATA_CENTER,
            capacityMW,
            firmLoadFactor: 0.80,
            firmPeakCoincidence: 1.0,
            flexLoadFactor: scenario.loadFactor,
            flexPeakCoincidence: scenario.peakCoincidence,
            onsiteGenerationMW: 0,
        };
    }
    return {
        ...DEFAULT_DATA_CENTER,
        capacityMW,
        firmLoadFactor: scenario.loadFactor,
        firmPeakCoincidence: scenario.peakCoincidence,
        flexLoadFactor: scenario.loadFactor,
        flexPeakCoincidence: scenario.peakCoincidence,
        onsiteGenerationMW: 0,
    };
}

// ============================================================
// RUN ONE UTILITY × SCENARIO × DATASET
// ============================================================
interface RunResult {
    capacityMW: number;
    monthlyBillFinal: number;
    baselineFinal: number;
    dcImpactMonthly: number;
    revAdequacyRatio: number;
    surplusOrDeficitPerMW: number;
    totalRevenue: number;
    totalCost: number;
    demandRevenue: number;
    energyRevenue: number;
    capacityCost: number;
    demandChargeFlowThroughPct: number; // What share of demand revenue flows through to ratepayers
}

function computeDemandFlowThroughPct(utility: Utility): number {
    // Mirrors calculations.ts:1307–1309 logic — kept inline so we can report
    // the flow-through % alongside scenario results without re-running the
    // private bill-impact path.
    const isRegulatedMarket = !utility.hasCapacityMarket && utility.marketType !== 'ercot';
    const base = isRegulatedMarket ? 0.90 : utility.marketType === 'ercot' ? 0.70 : 0.60;
    const HIGH_NBC_STATES = ['CA', 'NY', 'CT', 'MA', 'RI', 'NH'];
    const passthrough = HIGH_NBC_STATES.includes(utility.state) ? 0.60 : 1.0;
    return base * passthrough;
}

function runOne(
    profile: UtilityProfile,
    scenario: Scenario,
): RunResult | { error: string } {
    try {
        const utility = buildUtilityFromProfile(profile);
        const capacityMW = scenario.capacityResolver(profile);
        const dc = buildDataCenter(scenario, capacityMW);
        const tariff = profile.tariff;

        const trajectories = generateAllTrajectories(
            utility,
            dc,
            PROJECTION_YEARS,
            tariff,
            ESCALATION,
        );

        const target =
            scenario.series === 'flexible' ? trajectories.flexible : trajectories.unoptimized;
        const baseline = trajectories.baseline;
        const finalIdx = target.length - 1;
        const monthlyBillFinal = target[finalIdx].monthlyBill;
        const baselineFinal = baseline[finalIdx].monthlyBill;

        const ra: RevenueAdequacyResult = calculateRevenueAdequacy(
            capacityMW,
            scenario.loadFactor,
            scenario.peakCoincidence,
            tariff,
            utility,
            0,
        );

        const flowThrough = computeDemandFlowThroughPct(utility);

        return {
            capacityMW,
            monthlyBillFinal,
            baselineFinal,
            dcImpactMonthly: monthlyBillFinal - baselineFinal,
            revAdequacyRatio: ra.revenueAdequacyRatio,
            surplusOrDeficitPerMW: ra.surplusOrDeficitPerMW,
            totalRevenue: ra.totalRevenue,
            totalCost: ra.totalMarginalCost,
            demandRevenue: ra.demandChargeRevenue,
            energyRevenue: ra.energyChargeRevenue,
            capacityCost: ra.marginalCapacityCost,
            demandChargeFlowThroughPct: flowThrough,
        };
    } catch (err: unknown) {
        const msg = err instanceof Error ? err.message : String(err);
        return { error: msg };
    }
}

// ============================================================
// MAIN
// ============================================================
interface ScenarioDelta {
    scenario: string;
    kind: Scenario['kind'];
    capacity_mw: number | null;
    baseline: RunResult | { error: string };
    refreshed: RunResult | { error: string };
    delta: {
        bill_impact_abs: number | null;
        bill_impact_pct: number | null;
        rev_adequacy_ratio_abs: number | null;
        flow_through_pct_abs: number | null;
    };
    bucket: '<5%' | '5-10%' | '10-20%' | '>20%' | 'incalculable';
}

interface UtilityDelta {
    id: string;
    utility: string;
    state: string;
    iso_rto: string;
    last_verified_baseline: string;
    last_verified_refreshed: string;
    tariff_diff: Record<string, { baseline: unknown; refreshed: unknown }>;
    scenarios: ScenarioDelta[];
    max_abs_pct: number; // for sort
}

function bucketize(pct: number | null): ScenarioDelta['bucket'] {
    if (pct === null || !Number.isFinite(pct)) return 'incalculable';
    const a = Math.abs(pct);
    if (a < 0.05) return '<5%';
    if (a < 0.10) return '5-10%';
    if (a < 0.20) return '10-20%';
    return '>20%';
}

function pctDelta(baseline: number, refreshed: number): number | null {
    if (baseline === 0) return refreshed === 0 ? 0 : null;
    return (refreshed - baseline) / Math.abs(baseline);
}

function diffTariffFields(
    baseline: EnrichedLike,
    refreshed: EnrichedLike,
): UtilityDelta['tariff_diff'] {
    const fields: (keyof EnrichedLike)[] = [
        'peak_demand_charge',
        'off_peak_demand_charge',
        'energy_rate_peak',
        'energy_rate_off_peak',
        'blendedRatePerKWh',
        'min_load_mw',
        'data_center_specific',
    ];
    const out: UtilityDelta['tariff_diff'] = {};
    for (const f of fields) {
        const b = baseline[f];
        const r = refreshed[f];
        if (JSON.stringify(b) !== JSON.stringify(r)) {
            out[f as string] = { baseline: b, refreshed: r };
        }
    }
    // Also surface ratchet + take-or-pay (nested under protections)
    if (baseline.protections.ratchet_pct !== refreshed.protections.ratchet_pct) {
        out['protections.ratchet_pct'] = {
            baseline: baseline.protections.ratchet_pct,
            refreshed: refreshed.protections.ratchet_pct,
        };
    }
    if (baseline.protections.take_or_pay !== refreshed.protections.take_or_pay) {
        out['protections.take_or_pay'] = {
            baseline: baseline.protections.take_or_pay,
            refreshed: refreshed.protections.take_or_pay,
        };
    }
    if (baseline.protections.ciac_required !== refreshed.protections.ciac_required) {
        out['protections.ciac_required'] = {
            baseline: baseline.protections.ciac_required,
            refreshed: refreshed.protections.ciac_required,
        };
    }
    return out;
}

function main(): void {
    // Identify the 64 rescraped utilities
    const rescraped = GENERATED_TARIFFS.filter(
        (t) => t.last_verified && RESCRAPED_VERIFIED_DATES.has(t.last_verified),
    );
    console.error(`Detected ${rescraped.length} rescraped utilities`);

    const results: UtilityDelta[] = [];
    const utilityErrors: string[] = [];

    for (const refreshedTariff of rescraped) {
        const id = refreshedTariff.id;
        const baselineTariff = BASELINE_TARIFF_DATA.find((t) => t.id === id);

        if (!baselineTariff) {
            utilityErrors.push(
                `${id}: not present in Jan 2026 baseline (may be a post-Jan add) — skip`,
            );
            continue;
        }

        const refreshedProfile = buildProfileFromPool(id, GENERATED_TARIFFS as EnrichedLike[]);
        const baselineProfile = buildProfileFromPool(id, BASELINE_TARIFF_DATA as EnrichedLike[]);
        if (!refreshedProfile || !baselineProfile) {
            utilityErrors.push(
                `${id}: profile build failed (baseline=${!!baselineProfile}, refreshed=${!!refreshedProfile}) — skip`,
            );
            continue;
        }

        const tariff_diff = diffTariffFields(
            baselineTariff as EnrichedLike,
            refreshedTariff as EnrichedLike,
        );

        const scenarios: ScenarioDelta[] = [];
        let maxAbsPct = 0;

        for (const scenario of SCENARIOS) {
            const baselineRun = runOne(baselineProfile, scenario);
            const refreshedRun = runOne(refreshedProfile, scenario);

            let billDeltaAbs: number | null = null;
            let billDeltaPct: number | null = null;
            let raDeltaAbs: number | null = null;
            let ftDeltaAbs: number | null = null;
            let capacityMW: number | null = null;

            if ('error' in baselineRun || 'error' in refreshedRun) {
                // leave nulls
            } else {
                billDeltaAbs = refreshedRun.dcImpactMonthly - baselineRun.dcImpactMonthly;
                billDeltaPct = pctDelta(baselineRun.dcImpactMonthly, refreshedRun.dcImpactMonthly);
                raDeltaAbs = refreshedRun.revAdequacyRatio - baselineRun.revAdequacyRatio;
                ftDeltaAbs =
                    refreshedRun.demandChargeFlowThroughPct -
                    baselineRun.demandChargeFlowThroughPct;
                capacityMW = refreshedRun.capacityMW;
                if (billDeltaPct !== null && Math.abs(billDeltaPct) > maxAbsPct) {
                    maxAbsPct = Math.abs(billDeltaPct);
                }
            }

            scenarios.push({
                scenario: scenario.label,
                kind: scenario.kind,
                capacity_mw: capacityMW,
                baseline: baselineRun,
                refreshed: refreshedRun,
                delta: {
                    bill_impact_abs: billDeltaAbs,
                    bill_impact_pct: billDeltaPct,
                    rev_adequacy_ratio_abs: raDeltaAbs,
                    flow_through_pct_abs: ftDeltaAbs,
                },
                bucket: bucketize(billDeltaPct),
            });
        }

        results.push({
            id,
            utility: refreshedTariff.utility,
            state: refreshedTariff.state,
            iso_rto: refreshedTariff.iso_rto,
            last_verified_baseline: baselineTariff.last_verified ?? 'unknown',
            last_verified_refreshed: refreshedTariff.last_verified ?? 'unknown',
            tariff_diff,
            scenarios,
            max_abs_pct: maxAbsPct,
        });
    }

    // Aggregate bucket distribution
    const bucketCounts: Record<ScenarioDelta['bucket'], number> = {
        '<5%': 0,
        '5-10%': 0,
        '10-20%': 0,
        '>20%': 0,
        incalculable: 0,
    };
    let totalScenarios = 0;
    for (const u of results) {
        for (const s of u.scenarios) {
            bucketCounts[s.bucket]++;
            totalScenarios++;
        }
    }

    // Per-utility bucket: pick the worst scenario bucket for that utility (incalculable counts separately)
    const utilityBuckets: Record<string, number> = {
        '<5%': 0,
        '5-10%': 0,
        '10-20%': 0,
        '>20%': 0,
        incalculable: 0,
    };
    for (const u of results) {
        if (u.max_abs_pct === 0 && u.scenarios.every((s) => s.bucket === 'incalculable')) {
            utilityBuckets['incalculable']++;
            continue;
        }
        utilityBuckets[bucketize(u.max_abs_pct === 0 ? 0 : u.max_abs_pct > 0 ? u.max_abs_pct : 0)]++;
    }

    // Sort utilities by max delta pct desc (worst first)
    results.sort((a, b) => b.max_abs_pct - a.max_abs_pct);

    const summary = {
        generated: new Date().toISOString(),
        baseline_sha: 'ab74e83',
        baseline_description: 'Pre-Hermes-rescrape Jan 2026 (Records: 89, all last_verified 2026-01-31 or 2026-02-01)',
        refreshed_description: `Current main (Records: ${GENERATED_TARIFFS.length}, rescraped: ${rescraped.length})`,
        methodology_version: 'v2.1 (Gemini-blessed 2026-05-14)',
        rescraped_count_detected: rescraped.length,
        utility_results_count: results.length,
        scenarios_per_utility: SCENARIOS.length,
        total_scenarios_run: totalScenarios,
        scenario_bucket_counts: bucketCounts,
        utility_bucket_counts_by_worst_scenario: utilityBuckets,
        utility_errors: utilityErrors,
    };

    // Write JSON output
    const docsPath = join(__dirname, '..', '..', 'docs', 'track-e-deltas-2026-05-27.json');
    writeFileSync(
        docsPath,
        JSON.stringify({ summary, utilities: results }, null, 2),
        'utf8',
    );

    // Stdout summary
    console.log('# Wave 1 Track A — Delta Validation Summary');
    console.log('');
    console.log(`Generated: ${summary.generated}`);
    console.log(`Baseline SHA: ${summary.baseline_sha}`);
    console.log(`Rescraped utilities detected: ${summary.rescraped_count_detected}`);
    console.log(`Utility results: ${summary.utility_results_count}`);
    console.log(`Total scenarios run: ${summary.total_scenarios_run}`);
    console.log('');
    console.log('Scenario bucket distribution (by bill-impact delta %):');
    for (const [k, v] of Object.entries(bucketCounts)) {
        console.log(`  ${k.padEnd(14)} ${v}`);
    }
    console.log('');
    console.log('Utility bucket distribution (by WORST scenario per utility):');
    for (const [k, v] of Object.entries(utilityBuckets)) {
        console.log(`  ${k.padEnd(14)} ${v}`);
    }
    console.log('');
    console.log('Top 10 utilities by max delta:');
    for (const u of results.slice(0, 10)) {
        console.log(
            `  ${u.id.padEnd(45)}  max ${(u.max_abs_pct * 100).toFixed(1).padStart(6)}%  state=${u.state}  iso=${u.iso_rto}`,
        );
    }
    console.log('');
    if (utilityErrors.length > 0) {
        console.log(`Skipped/errored (${utilityErrors.length}):`);
        for (const e of utilityErrors) console.log(`  - ${e}`);
    }
    console.log('');
    console.log(`Full JSON: ${docsPath}`);
}

main();
